
modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPL-3.0"
issueTrackerURL = "https://github.com/DxsSucuk/CCBX/issues"
logoFile = "pack.png"
[[mods]] #mandatory
# The modid of the mod
modId = "ccbx" #mandatory
version = "1.0" #mandatory
authors= "Presti"
# A display name for the mod
displayName = "CC: BallistX" #mandatory
displayURL = "https://presti.me"
# The description text for the mod (multi line!) (#mandatory)
description = '''
 A mod that adds a peripheral for CC: Tweaked to allow control over BallistX silos.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.ccbx]] #optional
# the modid of the dependency
modId = "forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[36,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"
# Here's another dependency
[[dependencies.ccbx]]
modId = "computercraft"
mandatory = true
versionRange = "1.101.3"
ordering = "NONE"
side = "BOTH"
[[dependencies.ccbx]]
modId = "ballistix"
mandatory = true
versionRange = "[1.19.2-0.6,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ccbx]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "1.19.2"
ordering = "NONE"
side = "BOTH"
[[dependencies.ccbx]]
modId="electrodynamics"
mandatory=true
versionRange="[1.19.2-0.7,)"
ordering="NONE"
side="BOTH"